### ISSUE TITLE
Can't reach docker image

### ISSUE THREAD

**Issue by jayanty** [brilliant-monkey/frigate-clips#1]
Error trying to start docker:

`Error response from daemon: Get "https://brilliantmonkey.azurecr.io/v2/": dial tcp: lookup brilliantmonkey.azurecr.io on 10.1.10.81:53: no such host`

Tried using both of these image paths:

- image: brilliantmonkey.azurecr.io/frigate/clips:0.0.1
- image: brilliantmonkey.azurecr.io/frigate/clips:0.0.2

**Comment by johnmarksilly** [comment]
Sorry I updated the container registry to use Github. Forgot to change the docker-compose.yml

ghcr.io/brilliant-monkey/frigate-clips:0.0.2
